/* GENERATED by tools/sync-role-avatars.mjs. Source SHA256: e90e7c54f5e236e366be30727f4594c1b03401c5f44aa37ef723a86c2f23b2af */
(function(root){
const exports = {};
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.resolveWorkflowRole = exports.path = exports.resolve = exports.roles = void 0;
exports.roles = Object.freeze([
    "lead", "researcher", "analyst", "reviewer", "risk", "coder", "macro", "quant",
    "execution", "data", "sentiment", "onchain", "portfolio", "backtest", "security",
    "connector", "prediction", "futures", "equities", "evolution",
]);
const aliases = [
    ["risk", /\b(risk|guard)\b|风控|风险/],
    ["security", /\b(security|secure)\b|安全/],
    ["backtest", /\b(backtest(?:er|ing)?|replay)\b|回测|回放/],
    ["macro", /\b(macro|macroeconomic)\b|宏观/],
    ["quant", /\b(quant|quantitative|factor)\b|量化|因子/],
    ["execution", /\b(execution|executor|execute|trader)\b|执行|交易员/],
    ["data", /\b(data)\b|数据/],
    ["sentiment", /\b(sentiment|social)\b|舆情|情绪|社交/],
    ["onchain", /\b(on\s*chain|blockchain|defi)\b|链上/],
    ["portfolio", /\b(portfolio|allocation|allocator)\b|组合|配置师/],
    ["connector", /\b(connector|integration|adapter)\b|连接器|适配器|接入/],
    ["prediction", /\b(prediction|polymarket|forecast)\b|预测/],
    ["futures", /\b(futures?|perpetual|perp|derivatives?)\b|期货|永续|衍生品/],
    ["equities", /\b(equities|equity|stocks?)\b|股票|证券/],
    ["evolution", /\b(evolution|evolver|evolve|optimizer|tuner)\b|进化|演化/],
    ["reviewer", /\b(review(?:er)?|critic|auditor)\b|审阅|审查|复核|评审/],
    ["coder", /\b(coding|coder|code|developer|programmer|engineer)\b|编码|代码|开发|程序员/],
    ["lead", /\b(lead|leader|coordinator|orchestrator|planner|nerya)\b|主控|主脑|队长|协调|总控/],
    ["researcher", /\b(research(?:er)?|explorer)\b|研究|调研/],
    ["analyst", /\b(analyst|analysis|market)\b|分析|市场/],
];
function resolve(name = "") {
    const value = String(name ?? "").normalize("NFKC")
        .replace(/([a-z])([A-Z])/g, "$1 $2").toLowerCase()
        .replace(/[^\p{L}\p{N}]+/gu, " ").trim();
    if (!value)
        return "lead";
    if (exports.roles.includes(value))
        return value;
    const match = aliases.find(([, pattern]) => pattern.test(value));
    if (match)
        return match[0];
    let hash = 2166136261;
    for (let i = 0; i < value.length; i++)
        hash = Math.imul(hash ^ value.charCodeAt(i), 16777619);
    return exports.roles[(hash >>> 0) % exports.roles.length];
}
exports.resolve = resolve;
function path(name) {
    return `assets/agent-avatars/${resolve(name)}.png`;
}
exports.path = path;
function resolveWorkflowRole(node) {
    if (node.resource === "runtime")
        return "lead";
    if (node.resource.startsWith("role/"))
        return resolve(node.resource.slice(5));
    if (node.resource.startsWith("prompt/"))
        return resolve(node.resource.split("/").pop()?.replace(/(?:\.agent)?\.md$/i, ""));
    return resolve(node.title);
}
exports.resolveWorkflowRole = resolveWorkflowRole;

if(typeof module !== 'undefined' && module.exports) module.exports = exports;
else root.NeryaAvatars = exports;
})(typeof window !== 'undefined' ? window : globalThis);
