#!/usr/bin/env node
// Source-backed manual. Keep the public /docs.html URL and historical anchors.
import { readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { sections, render, copy, escape } from '../src/data/manual.mjs';
const output = fileURLToPath(new URL('../docs.html', import.meta.url));
const html = `<!doctype html>
<html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#faf9fc"><title>Nerya Docs · Agent 与 SDK</title><meta name="description" content="Nerya Agent 与 SDK 开发文档：安装、原生 Agent、会话与事件、工具与 Skills、策略、图表产物和安全边界。"><link rel="icon" href="/assets/nerya-logo.webp"><script src="/landing-theme.js"></script><link rel="stylesheet" href="/docs-v2.css"><script defer src="/docs-v2.js"></script></head>
<body><a class="skip-link" href="#doc-content">${copy('跳到文档','Skip to documentation')}</a>
<header class="docs-header"><a href="/" class="brand"><img src="/assets/nerya-logo.webp" alt="" width="30" height="30">nerya <span>docs</span></a><div class="docs-header-actions"><a href="/">${copy('返回官网','Website')}</a><button id="theme-toggle" aria-label="切换主题 / Switch theme" aria-pressed="false">◐</button><button id="docs-language" aria-label="Switch language / 切换语言">EN</button><button id="docs-menu" aria-controls="docs-sidebar" aria-expanded="false">${copy('目录','Contents')}</button></div></header>
<div class="docs-layout"><aside class="docs-sidebar" id="docs-sidebar"><label class="search-label" for="docs-search">${copy('搜索文档','Search documentation')}<kbd>/</kbd></label><input id="docs-search" type="search" autocomplete="off" placeholder="Agent、SDK、图表…" aria-describedby="docs-search-status"><p id="docs-search-status" class="search-status" role="status"></p><nav aria-label="文档章节 / Documentation chapters">${sections.map((s,i)=>`<a href="#${s.id}" data-doc-link="${s.id}"><span>${String(i+1).padStart(2,'0')}</span>${copy(...s.title)}</a>`).join('')}</nav><div class="sidebar-note">${copy('依据当前源码整理','Based on the current source')}<strong>2026.09.26</strong>${copy('示例不自动连接账户或提交交易','Examples do not automatically connect accounts or submit trades')}</div></aside>
<main id="doc-content"><div class="docs-hero"><div class="doc-eyebrow">NERYA / DEVELOPER MANUAL</div><h1>${copy('从一次对话<br>到可追溯的工作流','From a conversation<br>to a traceable workflow',true)}</h1><p>${copy('用 Agent 完成研究与策略任务，用 SDK 接入同一个运行时。工具调用、会话记录、图表和报告，都有各自清晰的契约。','Use the Agent for research and strategy work. Use the SDK to reach the same runtime. Tool calls, session history, charts and reports each have an explicit contract.')}</p><div class="doc-entry-links"><a href="#quickstart">${copy('开始使用','Get started')} ↗</a><a href="#sdk">Agent SDK ↗</a><a href="#artifacts">${copy('卡片与图表','Cards & charts')} ↗</a></div></div>
${sections.map((s,i)=>`<section class="doc-section" id="${s.id}">${(s.aliases||[]).map(a=>`<span id="${a}" class="anchor-alias"></span>`).join('')}<div class="section-number">${String(i+1).padStart(2,'0')} / ${escape(s.tag)}</div><h2><a href="#${s.id}" aria-label="链接到此章节 / Link to this section">#</a>${copy(...s.title)}</h2>${s.content.map(render).join('')}</section>`).join('')}
<footer class="docs-footer">${copy('本文描述当前工作树中的接口，不把未验证的包发布、连接器或收益当作已验证事实。','This manual describes the current working-tree interfaces. Package publication, connector availability and performance are not presented as independently verified facts.')}<a href="/">← ${copy('返回 Nerya','Back to Nerya')}</a></footer></main></div><button id="docs-top" aria-label="返回顶部 / Back to top">↑</button><div id="docs-copy-status" class="copy-status" role="status"></div></body></html>\n`;
if (process.argv.includes('--check')) {
  if (await readFile(output,'utf8') !== html) throw new Error('docs.html is stale: run node tools/render-docs.mjs');
  console.log(`PASS: generated bilingual manual, ${sections.length} source-backed sections.`);
} else { await writeFile(output,html); console.log(`Generated docs.html: ${sections.length} bilingual sections.`); }
