// Canonical geometry lives in the Agent. The generated asset ships with the
// static site; visitors never need the sibling repository or a network font.
import { readFile, writeFile } from 'node:fs/promises';
import { createHash } from 'node:crypto';
const source = new URL('../../agent/dashboard/components/icon-paths.json', import.meta.url);
const destination = new URL('../icon-paths.js', import.meta.url);
const raw = await readFile(source, 'utf8');
const paths = JSON.parse(raw);
for (const [name, path] of Object.entries(paths)) {
  if (!/^[a-z][a-zA-Z]*$/.test(name) || typeof path !== 'string' || !/^M[0-9. ,A-Za-z-]+$/.test(path)) throw new Error(`Invalid icon: ${name}`);
}
const sha = createHash('sha256').update(raw).digest('hex');
const content = `/* GENERATED by tools/sync-icons.mjs. Source SHA256: ${sha} */\nwindow.NeryaIconPaths = Object.freeze(${JSON.stringify(paths)});\n`;
if (process.argv.includes('--check')) {
  if (await readFile(destination, 'utf8') !== content) throw new Error('Icon geometry drift: run npm run sync:icons');
  console.log(`PASS: ${Object.keys(paths).length} icons match the Agent source (${sha.slice(0, 12)})`);
} else {
  await writeFile(destination, content);
  console.log(`Synced ${Object.keys(paths).length} Nerya Outline icons`);
}
